# Generated by Django 2.2.5 on 2019-09-29 16:04

from django.db import migrations
import os


class Migration(migrations.Migration):
    # This is a data migration as shown here https://stackoverflow.com/a/53261943
    # in order to create an admin user.
    dependencies = [
        ('auth', '0001_initial')
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username=os.environ.get("SUPERUSER_USERNAME"),
            email=os.environ.get("SUPERUSER_EMAIL"),
            password=os.environ.get("SUPERUSER_PASSWORD"))

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
