# Generated by Django 2.2.5 on 2019-10-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaydays', '0002_awayplan_location'),
    ]

    # Add a custom "exclusion" constraint
    # https://www.postgresql.org/docs/9.0/sql-createtable.html#SQL-CREATETABLE-EXCLUDE
    #
    # This means that the database will not accept two
    # awayplans for the same location with overlapping
    # dates unless all but one of them is cancelled.
    create_exclusion_index = """
        CREATE EXTENSION btree_gist;
        ALTER TABLE awaydays_awayplan 
            ADD CONSTRAINT unique_daterange
            EXCLUDE USING gist (
                location_id WITH =, 
                tstzrange(start_date, end_date, '[]') WITH && 
            ) WHERE (cancelled = FALSE);
    """

    operations = [
        migrations.RunSQL(create_exclusion_index)
    ]
